# Generated by Django 3.0.5 on 2020-05-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0002_articletags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ArticleTags',
        ),
        migrations.AddField(
            model_name='article',
            name='main_tags',
            field=models.ManyToManyField(blank=True, null=True, to='Wobliczu.MainTags'),
        ),
        migrations.AddField(
            model_name='article',
            name='secondary_tags',
            field=models.ManyToManyField(blank=True, null=True, to='Wobliczu.SecondaryTags'),
        ),
    ]
