# Generated by Django 3.0.5 on 2020-05-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0005_auto_20200504_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='articleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfArticles', models.IntegerField(verbose_name='numberOfArticles')),
            ],
        ),
    ]
