# Generated by Django 3.0.5 on 2020-05-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0006_articleuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='articleUser',
        ),
    ]
