# Generated by Django 3.0.5 on 2020-05-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0009_auto_20200504_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='numberOfViews',
            field=models.IntegerField(default=0, max_length=7),
        ),
    ]
