# Generated by Django 3.0.5 on 2020-05-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0010_article_numberofviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='numberOfViews',
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0, max_length=6),
        ),
    ]
