# Generated by Django 3.0.5 on 2020-05-05 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0011_auto_20200505_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 5, 23, 10, 28, 975443)),
        ),
    ]
