# Generated by Django 3.0.5 on 2020-05-05 21:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0014_auto_20200505_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 5, 21, 31, 49, 672385, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 23, 31, 49, 672385)),
        ),
    ]
