# Generated by Django 3.0.5 on 2020-05-05 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0017_auto_20200505_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 23, 35, 56, 407992)),
        ),
    ]
