# Generated by Django 3.0.5 on 2020-05-05 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0019_auto_20200505_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleuser',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 0, 48, 35, 152992)),
        ),
    ]
