# Generated by Django 3.0.5 on 2020-05-06 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0021_auto_20200506_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 22, 13, 37, 534971)),
        ),
    ]
