# Generated by Django 3.0.5 on 2020-05-08 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0024_auto_20200508_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_section_four',
            field=models.ImageField(blank=True, null=True, upload_to='media/sect4/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_section_three',
            field=models.ImageField(blank=True, null=True, upload_to='media/sect3/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_section_two',
            field=models.ImageField(blank=True, null=True, upload_to='media/sect2/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_section_four',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_section_three',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_section_two',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 14, 11, 27, 264064)),
        ),
    ]
