# Generated by Django 3.0.5 on 2020-05-08 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0030_auto_20200508_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 0, 30, 7, 792407)),
        ),
    ]
