# Generated by Django 3.0.5 on 2020-05-09 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0032_auto_20200509_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 2, 31, 35, 900006)),
        ),
    ]
