# Generated by Django 3.0.5 on 2020-05-09 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0033_auto_20200509_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='header',
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 1, 33, 9, 10211)),
        ),
    ]
