# Generated by Django 3.0.5 on 2020-05-10 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0038_auto_20200510_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustTryin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 3, 40, 59, 718570)),
        ),
    ]
