# Generated by Django 3.0.5 on 2020-05-10 01:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0039_auto_20200510_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 3, 48, 14, 171930)),
        ),
        migrations.CreateModel(
            name='ChujJebany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chuj', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wobliczu.Article')),
            ],
        ),
    ]
