# Generated by Django 3.0.5 on 2020-05-10 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0040_auto_20200510_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chujjebany',
            name='model',
        ),
        migrations.DeleteModel(
            name='JustTryin',
        ),
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 3, 51, 44, 181773)),
        ),
        migrations.DeleteModel(
            name='ChujJebany',
        ),
    ]
