# Generated by Django 3.0.5 on 2020-05-10 23:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0042_auto_20200511_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='shown_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_requests_created', to='Wobliczu.SecondaryTags'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_desc',
            field=models.CharField(max_length=650),
        ),
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 1, 40, 9, 881188)),
        ),
    ]
