# Generated by Django 3.0.5 on 2020-05-11 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0043_auto_20200511_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 12, 1, 48, 34, 292044)),
        ),
    ]
