# Generated by Django 3.0.5 on 2020-05-11 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0044_auto_20200512_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 12, 1, 53, 58, 556286)),
        ),
    ]
