# Generated by Django 3.0.5 on 2020-05-12 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0046_auto_20200512_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 12, 2, 6, 41, 113321)),
        ),
    ]
