# Generated by Django 3.0.5 on 2020-05-18 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0048_auto_20200518_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='shown_tag',
        ),
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 1, 11, 59, 350176)),
        ),
    ]
