# Generated by Django 3.0.5 on 2020-06-16 22:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0050_auto_20200613_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Wobliczu.Comment'),
        ),
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 0, 37, 16, 879912)),
        ),
        migrations.DeleteModel(
            name='CommentAnswers',
        ),
    ]
