# Generated by Django 3.0.5 on 2020-06-21 22:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0053_auto_20200621_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Wobliczu.Comment'),
        ),
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 0, 51, 52, 324177)),
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
