# Generated by Django 3.0.7 on 2020-06-26 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0054_auto_20200622_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 23, 38, 11, 933120)),
        ),
    ]
