# Generated by Django 3.0.7 on 2020-06-27 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0057_auto_20200627_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 23, 4, 15, 677556)),
        ),
    ]
