# Generated by Django 3.0.5 on 2020-06-28 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0057_auto_20200627_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_journalist',
            field=models.BooleanField(default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 1, 11, 19, 9052)),
        ),
    ]
