# Generated by Django 3.0.7 on 2020-06-30 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0058_auto_20200629_0111'),
        ('Wobliczu', '0058_auto_20200627_2304'),
    ]

    operations = [
    ]
