# Generated by Django 3.0.5 on 2020-07-03 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0059_merge_20200630_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 18, 39, 8, 475343)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='number_of_replies',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
