# Generated by Django 3.0.5 on 2020-07-03 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0061_auto_20200703_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 19, 18, 26, 268230)),
        ),
    ]
