# Generated by Django 3.0.5 on 2020-07-03 22:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0063_auto_20200703_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 3, 22, 55, 40, 609136, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 4, 0, 55, 40, 609136)),
        ),
    ]
