# Generated by Django 3.0.5 on 2020-07-10 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0059_merge_20200701_0107'),
        ('Wobliczu', '0067_auto_20200704_1737'),
    ]

    operations = [
    ]
