# Generated by Django 3.0.5 on 2020-07-28 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0072_auto_20200728_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_section_four',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_section_three',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_section_two',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text_section_four',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text_section_three',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text_section_two',
        ),
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 15, 29, 46, 60264)),
        ),
    ]
