# Generated by Django 3.0.5 on 2020-07-29 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0074_auto_20200729_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='ID',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 11, 20, 43, 369895)),
        ),
    ]
