# Generated by Django 3.0.8 on 2020-08-07 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0075_auto_20200729_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 0, 37, 35, 289381)),
        ),
    ]
