# Generated by Django 3.0.8 on 2020-08-15 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0079_auto_20200812_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 15, 22, 2, 56, 897075)),
        ),
    ]
