# Generated by Django 3.0.8 on 2020-08-19 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wobliczu', '0080_auto_20200815_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleuser',
            name='last_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 14, 51, 52, 375358)),
        ),
    ]
